name: amuse-py313
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attr=2.5.2
  - binutils=2.44
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - bison=3.8.2
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-compiler=1.10.0
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.8.3
  - cfitsio=4.6.2
  - cftime=1.6.4
  - cmake=4.1.2
  - conda-gcc-specs=13.4.0
  - coreutils=9.5
  - curl=8.14.1
  - cxx-compiler=1.10.0
  - docutils=0.22.2
  - fftw=3.3.10
  - flex=2.6.4
  - fortran-compiler=1.10.0
  - gcc=13.4.0
  - gcc_impl_linux-64=13.4.0
  - gcc_linux-64=13.4.0
  - gfortran=13.4.0
  - gfortran_impl_linux-64=13.4.0
  - gfortran_linux-64=13.4.0
  - gmp=6.3.0
  - gsl=2.8
  - gxx=13.4.0
  - gxx_impl_linux-64=13.4.0
  - gxx_linux-64=13.4.0
  - gzip=1.14
  - h5py=3.14.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - healpix_cxx=3.81
  - icu=75.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libaec=1.1.4
  - libblas=3.9.0
  - libcap=2.76
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libfabric=2.2.0
  - libfabric1=2.2.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.4.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libopenblas=0.3.30
  - libpmix=5.0.8
  - libsanitizer=13.4.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=13.4.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.9
  - libudev1=257.9
  - libuuid=2.41.2
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - m4=1.4.20
  - make=4.4.1
  - mpfr=4.2.1
  - mpi=1.0.1
  - mpi4py=4.1.0
  - ncurses=6.5
  - netcdf4=1.7.2
  - numpy=2.3.3
  - openmpi=5.0.8
  - openssl=3.5.4
  - patch=2.8
  - perl=5.32.1
  - pip=25.2
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - python=3.13.7
  - python_abi=3.13
  - qhull=2020.2
  - rdma-core=59.0
  - readline=8.2
  - rhash=1.4.6
  - snappy=1.2.2
  - sysroot_linux-64=2.34
  - tar=1.35
  - tk=8.6.13
  - tzdata=2025b
  - ucc=1.5.1
  - ucx=1.19.0
  - unzip=6.0
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - amuse-framework==2025.9.0
